CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS lemf_db;

GRANT ALL PRIVILEGES ON auth_db.* TO 'pot_user'@'%';
GRANT ALL PRIVILEGES ON lemf_db.* TO 'pot_user'@'%';
FLUSH PRIVILEGES;
